#:schema node_modules/wrangler/config-schema.json
name = "sublink-workers"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "854ac51f36be45628a8998b4a86eecc4" }
]

[assets]
directory = "./public"
